### PR TITLE
Fix/3 floating point precision

### PR DESCRIPTION
**Pull request by QuanTumli**
This is a draft PR for issue https://github.com/tspoke/typescript-open-location-code/issues/3.

At the moment, the following tests are failing:
- Validity Tests, testIsValid for `["WC2300+",false,false,false]`
- Validity Tests, testIsShort for `["WC2300+",false,false,false]`

According to the test data from https://github.com/google/open-location-code/blob/master/test_data/validityTests.csv the Plus Code `WC2300+` should be both `not valid` and `not short`.

### CODE REVIEW

**Review by jan25 — COMMENTED** [review]
LGTM. Thanks for picking this!
After some digging i found this PR in main repo https://github.com/google/open-location-code/pull/274/files#diff-52b656fef4fc135988d50b799ee8158d (It says no padding allowed for short codes). Probably that change was missed in this typescript library

**Comment by QuanTumli** [comment]
@jan25 Thank you for reviewing and digging into the main repo!

I just added the short "no padding allowed" check to the PR (https://github.com/tspoke/typescript-open-location-code/pull/4/commits/8db7af962743d64a152badae503e42a39a0b658f) and all tests are now green. :) 

Did a short update to the commit history, so it should look clean.

**Review by tspoke — APPROVED** [review]

**Comment by tspoke** [comment]
Thanks for your help, I went through the code and it LGTM!
Waiting for @jan25 to double check it before merging this PR.

Thanks again :)

**Comment by jan25** [comment]
LGTM as well. I checked with main repo changes
Thanks!

**Pull request merged**
